language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.16.1
  - bundle --version

rvm:
  - jruby-9.1.15.0
  - 2.2
  - 2.3
  - 2.4.3
  - 2.5.0

env:
  - LIBSODIUM_VERSION=1.0.0  # Minimum supported
  - LIBSODIUM_VERSION=1.0.16 # Latest released

matrix:
  fast_finish: true

branches:
  only:
    - master
